# for_problem2.py

for x in range(4,0):
    print(x)
else:
    print("循环结束后x的值"，x) # 报错